config/routes.rb
Rails.application.routes.draw do
  resources :order_statuses
  resources :runners
  resources :orders
  resources :orders
  resources :dimensions
  resources :order_statuses
  resources :materials
  resources :line_items
  resources :pallets do
    member do
      get 'price'
  end
    end
  resources :customers
  resources :employees
  resources :customer_statuses
  resources :supplier_statuses
  resources :employee_statuses
  resources :pallet_statuses
  resources :suppliers
  resources :pallet_grades
  resources :titles

  get 'dashboard/index'
  get 'reports/new_orders_monthly'
  get 'reports/cancelled_orders_monthly'
  get 'reports/inactive_customers_monthly'
  get 'reports/inactive_suppliers_monthly'
  get 'reports/new_customers_monthly'
  get 'reports/new_suppliers_monthly'

   root 'dashboard#index'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
end

app/views/dashboard/index.html.erb
<html lang="en">
<!-- begin Header-->
<header>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Grembowiec & Associates Pallet System" >
  <meta name="author" content="MetaBear Systems">
  <!--<div class="page-header" align="center">-->
  <!--<div class="row-fluid">-->
  <!--<h1>G.A.P.S.</h1>-->
  <!--</div>-->
  <!--</div>-->
</header>
<!--end header-->
<!--begin body -->
<body>

<div class="page-header" align="center">
  <div class="row-fluid">
    <%= link_to image_tag("GAPS.JPG"), {:class=> "img-thumbnail" } %>
  </div>
</div>


<div id = "myCarousel" class = "carousel slide animated fadeIn" data-ride="carousel" >
  <ol class="carousel-indicators">
    <li class="active" data-slide-to="0" data-target="#myCarousel"></li>
    <li class="" data-slide-to="1" data-target="#myCarousel"></li>
    <li class="" data-slide-to="2" data-target="#myCarousel"></li>
  </ol>
  <div class = "carousel-inner">
    <div class="item active">
      <%= link_to image_tag("p1.jpg", :alt => "First Slide"), {:class => "first-slide"} %>
      <div class="container">
        <div class="carousel-caption">
          <h2 align="center">Click to add a new customer</h2>
          <%=  link_to 'ADD CUSTOMER', new_customer_path, :class => 'btn btn-info btn-lg' %>
        </div>
      </div>
    </div>
    <div class="item">
      <%= link_to image_tag("p2.jpg", :alt => "Second Slide"), {:class => "second-slide"} %>
      <div class="container">
        <div class="carousel-caption">
          <h2 align="center">Click to add a new supplier</h2>
          <%= link_to 'ADD SUPPLIER', new_supplier_path, :class => 'btn btn-info btn-lg' %>
        </div>
      </div>
    </div>
    <div class="item">
      <%= link_to image_tag("p3.png", :alt => "Third Slide"), {:class => "third-slide"} %>
      <div class="container">
        <div class="carousel-caption">
          <h2 align="center">Click to add a new order</h2>
          <%= link_to 'ADD ORDER', new_order_path, :class => 'btn btn-info btn-lg' %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">

  <div class="col-xs-6 col-md-3">
    <a href="orders" class="thumbnail">
      <h4 align="center", class="custom_font">Orders</h4><!-- class thumbnail , no 1 -->
      <img <%= link_to image_tag("order.jpg"), {:class=> "img-thumbnail" } %>
    </a>
  </div>

  <div class="col-xs-6 col-md-3">
    <a href="customers" class="thumbnail">
      <h4 align="center", class="custom_font">Customers</h4><!-- class thumbnail , no 2 -->
      <img <%= link_to image_tag("customer.jpg"), {:class=> "img-thumbnail" } %>
    </a>
  </div>

  <div class="col-xs-6 col-md-3">
    <a href="employees" class="thumbnail" >
      <h4 align="center", class="custom_font">Employees</h4><!-- class thumbnail , no 3 -->
      <img <%= link_to image_tag("employee.jpg"), {:class=> "img-thumbnail"} %>
    </a>
  </div>

  <div class="col-xs-6 col-md-3">
    <a href="suppliers" class="thumbnail">
      <h4 align="center", class="custom_font">Suppliers</h4><!-- class thumbnail , no 4 -->
      <img alt="" <%= link_to image_tag("suppliers.jpg"), {:class=> "img-thumbnail" } %>
    </a>
  </div>

</div>



<!--<div class="container col-xs-3">-->
<!--<h2>Rounded Corners</h2>-->
<!--<div class="row">-->
<!--<div class="col-xs-3 col-xs-6">-->
<!--<%= link_to image_tag("Pallet.jpg"), {:class=> "img-thumbnail" } %>-->
<!--</div>-->
<!--</div>-->
<!--</div>-->


</body>
<!-- end body -->
</html>