config/routes.rb
Rails.application.routes.draw do
  resources :order_statuses
  resources :runners
  resources :orders
  resources :orders
  resources :dimensions
  resources :order_statuses
  resources :materials
  resources :line_items
  resources :pallets do
    member do
      get 'price'
  end
    end
  resources :customers
  resources :employees
  resources :customer_statuses
  resources :supplier_statuses
  resources :employee_statuses
  resources :pallet_statuses
  resources :suppliers
  resources :pallet_grades
  resources :titles

  get 'dashboard/index'
  get 'reports/new_orders_monthly'
  get 'reports/cancelled_orders_monthly'
  get 'reports/inactive_customers_monthly'
  get 'reports/inactive_suppliers_monthly'
  get 'reports/new_customers_monthly'
  get 'reports/new_suppliers_monthly'

   root 'dashboard#index'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :employee_status
  belongs_to :title
  has_many :customer_contacts
  has_many :customers, :through => :customer_contacts
  accepts_nested_attributes_for :customer_contacts,
                                :reject_if => :all_blank,
                                :allow_destroy => true
  accepts_nested_attributes_for :customers
  before_create { |employee| employee.employee_status_id = '1' };

  #Method
  def full_emp_name
    "#{fname} #{lname}"
  end
  def fname=(s)
    super s.titleize
  end
  def lname=(s)
    super s.titleize
  end
  def address=(s)
    super s.titleize
  end
  def city=(s)
    super s.titleize
  end

  #Validations
  validates :fname, :lname, :phone, :email, :address, :city,
            presence: true
  validates :phone,
            length: {minimum: 10, maximum: 11},
            numericality: true
  validates :fname, :lname, :city, :state,
            format: {with: /\A[a-zA-Z]+\z/}
  validates :city,
            length: {maximum:  22}
  validates_format_of :email,
                      :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  validates_format_of :address, :with => /[a-zA-Z\d ]/i,
                      :message => "can only contain letters and numbers."

end

app/models/title.rb
class Title < ActiveRecord::Base
  has_many :employees

  def position=(s)
    super s.titleize
  end


  validates :position,
    presence: true,
    format: {with: /\A[a-zA-Z]+\z/}

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.update(:employee_status_id => '2')
    #@employee.delete
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:employee_status_id, :title_id, :fname, :lname, :phone, :email, :address, :city, :state, :comment, customers_attributes: [:company_name,:customer_status_id, :fname, :lname, :phone, :address, :city, :state, :email, :comment])
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_customer_fields.html.erb
<div class="nested-fields">
<div class="form-group">
  <%= f.label :fname, 'First Name :', :class => 'control-label col-sm-2' %>
  <div class="col-sm-5">
    <%= f.text_field :fname, :class => 'form-control' %>
  </div>
</div>
<div class="form-group">
  <%= f.label :lname,'Last Name :', :class => 'control-label col-sm-2' %>
  <div class="col-sm-5">
    <%= f.text_field :lname, :class => 'form-control' %>
  </div>
</div>
<div class="form-group">
  <%= f.label :phone,'Phone :', :class => 'control-label col-sm-2' %>
  <div class="col-sm-5">
    <%= f.text_field :phone, :class => 'form-control',:placeholder => "e.g. 8323183180" %>
  </div>
</div>
<div class="form-group">
  <%= f.label :address,'Address :', :class => 'control-label col-sm-2' %>
  <div class="col-sm-5">
    <%= f.text_field :address, :class => 'form-control' %>
  </div>
</div>
<div class="form-group">
  <%= f.label :state,'State :', :class => 'control-label col-sm-2' %>
  <div class="col-sm-5">
    <%= f.select :state, options_for_select(us_states),{}, class: 'form-control' %>
  </div>
</div>
<div class="form-group">
  <%= f.label :city,'City :', :class => 'control-label col-sm-2' %>
  <div class="col-sm-5">
    <%= f.text_field :city, :class => 'form-control' %>
  </div>
</div>
<div class="form-group">
  <%= f.label :email,'E-mail :', :class => 'control-label col-sm-2' %>
  <div class="col-sm-5">
    <%= f.text_field :email, :class => 'form-control' %>
  </div>
</div>
<div class="form-group">
  <%= f.label 'Employee :', :class => 'col-sm-2 control-label' %>
  <div class="col-sm-5">
    <%= f.collection_select :employee_ids, Employee.where(:employee_status => '1'), :id, :fname, {} ,{class: "form-control"} %>
  </div>
</div>
<div class="form-group">
  <%= f.label :comment,'Comment :', :class => 'control-label col-sm-2' %>
  <div class="col-sm-5">
    <%= f.text_area :comment, :class => 'form-control' %>
  </div>
</div>
<div>
<%= link_to_remove_association "remove", f, :class => 'btn btn-info btn-xs'%>
</div>
</div>

app/views/employees/_form.html.erb
<hr>
<%= form_for @employee, :html => { :class => "form-horizontal employee" } do |f| %>

    <% if @employee.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @employee.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

    <div class="form-group">
      <%= f.label :employee_status_id,'Status :', :class => 'control-label col-sm-2' %>
      <div class="col-sm-2">
        <%= f.collection_select :employee_status_id, EmployeeStatus.all, :id, :description, {}, {class: 'form-control'} %>
      </div>
      <%= error_span(@employee[:title_id]) %>
    </div>

  <div class="form-group">
    <%= f.label :title_id,'*  ' 'Title :', :class => 'control-label col-sm-2' %>
    <div class="col-sm-2">
      <%= f.collection_select :title_id, Title.all, :id, :position, {}, {class: 'form-control'} %>
    </div>
    <%= error_span(@employee[:title_id]) %>
  </div>

      <div class="form-inline">
        <div class="form-group col-sm-4" >
          <%= f.label :fname,'*  ' 'First Name :', :class => 'control-label col-sm-6' %>
          <div class="col-sm-5">
            <%= f.text_field :fname, :class => 'form-control' %>
          </div>
          <%= error_span(@employee[:fname]) %>
        </div>
        <div class="form-group">
          <%= f.label :lname,'* ' 'Last Name :', :class => 'control-label col-sm-5' %>
          <div class="col-sm-5">
            <%= f.text_field :lname, :class => 'form-control' %>
          </div>
          <%= error_span(@employee[:lname]) %>
        </div>
      </div>
      <br>


  <div class="form-group">
    <%= f.label :phone,'*  ' 'Phone :', :class => 'control-label col-sm-2' %>
    <div class="col-sm-2">
      <%= f.text_field :phone, :class => 'form-control',:placeholder => "e.g. 8323183180" %>
    </div>
    <%= error_span(@employee[:phone]) %>
  </div>
  <div class="form-group">
    <%= f.label :email,"*  "'Email :', :class => 'control-label col-sm-2' %>
    <div class="col-sm-3">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%= error_span(@employee[:email]) %>
  </div>
  <div class="form-group">
    <%= f.label :address,'* ' 'Address :', :class => 'control-label col-sm-2' %>
    <div class="col-sm-3">
      <%= f.text_field :address, :class => 'form-control' %>
    </div>
    <%= error_span(@employee[:address]) %>
  </div>

    <div class="form-inline">
      <div class="form-group col-sm-4">
        <%= f.label :state,'*  ' 'State :', :class => 'control-label col-sm-6' %>
        <div class="col-sm-2">
          <%= f.select :state, options_for_select(us_states, @employee.state), {}, class: 'form-control'  %>
        </div>
        <%= error_span(@employee[:state]) %>
      </div>
      <div class="form-group">
        <%= f.label :city,'*  ' 'City :', :class => 'control-label col-sm-5' %>
        <div class="col-sm-3">
          <%= f.text_field :city, :class => 'form-control' %>
        </div>
        <%= error_span(@employee[:city]) %>
      </div>
    </div>
    <br>

  <div class="form-group">
    <%= f.label :comment,'Comment :', :class => 'control-label col-sm-2' %>
    <div class="col-sm-5">
      <%= f.text_area :comment, :class => 'form-control' %>
    </div>
    <%= error_span(@employee[:comment]) %>
  </div>

<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            employees_path, :class => 'btn btn-default' %><h4>* is required field</h4>

</div>
  </div>


<% end %>

app/views/employees/edit.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/employees/index.html.erb
<%- model_class = Employee -%>
<div class="container-fluid">
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  <hr>
</div>
<table class="table table-striped table-hover table-condensed" id="emp">
  <thead>
    <tr>
      <th>Name</th>
      <th><%= model_class.human_attribute_name(:title_id) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
      <th><%= model_class.human_attribute_name(:state) %></th>
      <th>Status</th>
      <th><%= model_class.human_attribute_name(:comment) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% for employee in @employees.all %>
      <tr>
        <td><%= link_to employee.full_emp_name, employee_path(employee) %></td>
        <td><%= employee.title.position %></td>
        <td><%= number_to_phone(employee.phone, area_code: true) %></td>
        <td><%= employee.email %></td>
        <td><%= employee.address %></td>
        <td><%= employee.city %></td>
        <td><%= employee.state %></td>
        <td><%= employee.employee_status.description %></td>
        <td id="comment"><%= employee.comment %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      employee_path(employee), :class => 'btn btn-success btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_employee_path(employee), :class => 'btn btn-update btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      employee_path(employee),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_employee_path,
            :class => 'btn btn-primary' %>
</div>

app/views/employees/new.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/employees/show.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => @employee.full_emp_name.titleize %></h1>
  <hr>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title_id) %>:</strong></dt>
  <dd><%= @employee.title.position %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= number_to_phone(@employee.phone, area_code: true) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @employee.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @employee.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
  <dd><%= @employee.city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:state) %>:</strong></dt>
  <dd><%= @employee.state %></dd>
  <dt><strong>Status:</strong></dt>
  <dd><%= @employee.employee_status.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:comment) %>:</strong></dt>
  <dd id="comment"><%= @employee.comment %></dd>
</dl>
<%= link_to t('.back', :default => t("helpers.links.back")),
            employees_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
            edit_employee_path(@employee), :class => 'btn btn-update' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
            employee_path(@employee),
            :method => 'delete',
            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
            :class => 'btn btn-danger' %>
<hr>
<div class="container-fluid col-xs-10 col-md-4">
  <h3>Customers</h3>
  <% if @employee.customers.all.count > 0 %>
  <table class="table table-striped table-hover table-condensed" id="cust_get">
    <thead>
    <tr>
      <th class="col-sm-2">Customer #</th>
      <th class="col-sm-4">Customer Name</th>
      <th class="col-sm-4">Company Name</th>
    </tr>
    </thead>
    <tbody>

    <% for customer in @employee.customers.all %>
        <tr>
          <td><%= customer.id %></td>
          <td><%= link_to customer.full_Cust_name, customer_path(customer)%></td>
          <td><%= customer.company_name %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
      <% else %>
     <h4><ul>****There are no customer provided****</ul></h4>
  <% end %>
  <%= link_to 'Add a New Customer', new_customer_path, :class => 'btn btn-primary'  %>

</div>