config/routes.rb
Rails.application.routes.draw do
  resources :order_statuses
  resources :runners
  resources :orders
  resources :orders
  resources :dimensions
  resources :order_statuses
  resources :materials
  resources :line_items
  resources :pallets do
    member do
      get 'price'
  end
    end
  resources :customers
  resources :employees
  resources :customer_statuses
  resources :supplier_statuses
  resources :employee_statuses
  resources :pallet_statuses
  resources :suppliers
  resources :pallet_grades
  resources :titles

  get 'dashboard/index'
  get 'reports/new_orders_monthly'
  get 'reports/cancelled_orders_monthly'
  get 'reports/inactive_customers_monthly'
  get 'reports/inactive_suppliers_monthly'
  get 'reports/new_customers_monthly'
  get 'reports/new_suppliers_monthly'

   root 'dashboard#index'

end

app/models/runner.rb
class Runner < ActiveRecord::Base
  has_many :pallets

  validates :number, :presence => true
  
end

app/controllers/runners_controller.rb
class RunnersController < ApplicationController
  before_action :set_runner, only: [:show, :edit, :update, :destroy]

  # GET /runners
  # GET /runners.json
  def index
    @runners = Runner.all
  end

  # GET /runners/1
  # GET /runners/1.json
  def show
    @runners = Runner.all
    respond_to do |format|
      format.html
      format.pdf do
        if @runner
          pdf = PalletRunnersPdf.new(@pallet_status, @pallet, @material, @runner, @dimension)
          send_data pdf.render, filename: "Pallet Runner Report.pdf", type: "application/pdf", disposition: "inline"
        end
      end
    end
  end

  # GET /runners/new
  def new
    @runner = Runner.new
  end

  # GET /runners/1/edit
  def edit
  end

  # POST /runners
  # POST /runners.json
  def create
    @runner = Runner.new(runner_params)

    respond_to do |format|
      if @runner.save
        format.html { redirect_to @runner, notice: 'Runner was successfully created.' }
        format.json { render :show, status: :created, location: @runner }
      else
        format.html { render :new }
        format.json { render json: @runner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /runners/1
  # PATCH/PUT /runners/1.json
  def update
    respond_to do |format|
      if @runner.update(runner_params)
        format.html { redirect_to @runner, notice: 'Runner was successfully updated.' }
        format.json { render :show, status: :ok, location: @runner }
      else
        format.html { render :edit }
        format.json { render json: @runner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /runners/1
  # DELETE /runners/1.json
  def destroy
    if @runner.pallets.count <= 0
    @runner.destroy
    respond_to do |format|
      format.html { redirect_to runners_url, notice: 'Runner was successfully destroyed.' }
      format.json { head :no_content }
    end
    else
      redirect_to runners_path, notice: "Cannot delete runner because apply to existing pallets"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_runner
      @runner = Runner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def runner_params
      params.require(:runner).permit(:number)
    end
end

app/helpers/runners_helper.rb
module RunnersHelper
end

app/views/runners/_form.html.erb
<hr>
<%= form_for @runner, :html => { :class => "form-horizontal runner" } do |f| %>

    <% if @runner.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@runner.errors.count, "error") %> prohibited this runner from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @runner.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :number, '*' 'Number of runners: ', :class => 'control-label col-sm-2' %>
    <div class="col-sm-1">
      <%= f.text_field :number, :class => 'form-control' %>
    </div>
    <%= error_span(@runner[:number]) %>
  </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                    runners_path, :class => 'btn btn-default' %>
        <h4>* required fields</h4>
      </div>
    </div>

<% end %>

app/views/runners/edit.html.erb
<%- model_class = Runner -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/runners/index.html.erb
<%- model_class = Runner -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  <hr>
</div>

<div class="container-fluid col-xs-12 col-md-5" >
  <table class="table table-striped" id="run_table">
    <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:number) %></th>
      <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <% @runners.each do |runner| %>
        <tr>
          <td><%= link_to runner.number, runner_path(runner) %></td>
          <td>
            <%= link_to t('.show', :default => t("helpers.links.show")),
                        runner_path(runner), :class => 'btn btn-success btn-xs' %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_runner_path(runner), :class => 'btn btn-update btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        runner_path(runner),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
            <%= link_to 'Pallets', runner_path(runner, format: "pdf"),:class => "btn btn-pdf btn-xs"%>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_runner_path,
              :class => 'btn btn-primary' %>
</div>

app/views/runners/new.html.erb
<%- model_class = Runner -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/runners/show.html.erb
<%- model_class = Runner -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
  <hr>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:number) %>:</strong></dt>
  <dd><%= @runner.number %></dd>
</dl>
<br><br>
<%= link_to t('.back', :default => t("helpers.links.back")),
              runners_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_runner_path(@runner), :class => 'btn btn-update' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              runner_path(@runner),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>