config/routes.rb
Rails.application.routes.draw do
  resources :order_statuses
  resources :runners
  resources :orders
  resources :orders
  resources :dimensions
  resources :order_statuses
  resources :materials
  resources :line_items
  resources :pallets do
    member do
      get 'price'
  end
    end
  resources :customers
  resources :employees
  resources :customer_statuses
  resources :supplier_statuses
  resources :employee_statuses
  resources :pallet_statuses
  resources :suppliers
  resources :pallet_grades
  resources :titles

  get 'dashboard/index'
  get 'reports/new_orders_monthly'
  get 'reports/cancelled_orders_monthly'
  get 'reports/inactive_customers_monthly'
  get 'reports/inactive_suppliers_monthly'
  get 'reports/new_customers_monthly'
  get 'reports/new_suppliers_monthly'

   root 'dashboard#index'

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :pallet
  belongs_to :order
  before_save :calc_total
  before_save :this_date

  validates :quantity, presence: true
  validates_numericality_of :quantity,
                            :greater_than_or_equal_to =>  0

def calc_total
  self.line_item_total= self.pallet.price * self.quantity
end
  def this_date
    self.date = Time.now
  end


end

app/controllers/line_items_controller.rb
  class LineItemsController < ApplicationController
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @line_item = LineItem.new(line_item_params)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item, notice: 'Line item was successfully created.' }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url, notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:order_id, :pallet_id, :quantity, :line_item_total, :date)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<hr>
<%= form_for @line_item, :html => { :class => "form-horizontal line_item" } do |f| %>

    <% if @line_item.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @line_item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :pallet_id,'*' ' Pallet :', :class => 'control-label col-sm-2' %>
    <div class="col-sm-4">
      <%= f.collection_select :pallet_id, Pallet.where(:pallet_status_id => '1'), :id,:id, {}, {class: 'form-control'}%>
    </div>
    <%= error_span(@line_item[:pallet_id]) %>
  </div>
  <div class="form-group">
    <%= f.label :quantity,'*' 'Quantity :', :class => 'control-label col-sm-2' %>
    <div class="col-sm-1">
      <%= f.number_field :quantity, :class => 'form-control' %>
    </div>
    <%= error_span(@line_item[:quantity]) %>
  </div>
  <div class="form-group">
    <%= f.label :line_item_total, '*' 'Line Item Total :', :class => 'control-label col-sm-2' %>
    <div class="col-sm-2">
      <%= f.text_field :line_item_total, :class => 'form-control' %>
    </div>
    <%= error_span(@line_item[:line_item_total]) %>
  </div>
  <div class="form-group">
    <%= f.label :date,'*' 'Date :', :class => 'control-label col-sm-2' %>
    <div class="col-sm-5">
      <%= f.date_select :date, :class => 'form-control' %>
    </div>
    <%= error_span(@line_item[:date]) %>
  </div>
  <div class="form-group">
    <%= f.label :order_id,'*' 'Order :', :class => 'control-label col-sm-2' %>
    <div class="col-sm-4">
      <%= f.collection_select :order_id, Order.where(:order_status_id => '1'), :id, :id,{},{class: 'form-control'} %>
    </div>
    <%= error_span(@line_item[:order_id]) %>
  </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            line_items_path, :class => 'btn btn-default' %>
        <h4>* is required field</h4>
      </div>
    </div>

<% end %>

app/views/line_items/edit.html.erb
<%- model_class = LineItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/line_items/index.html.erb
<%- model_class = LineItem -%>
<div class="container-fluid">
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  <hr>
</div>
<table class="table table-striped" id="LT_table">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:pallet_id) %></th>
      <th><%= model_class.human_attribute_name(:quantity) %></th>
      <th><%= model_class.human_attribute_name(:line_item_total) %></th>
      <th><%= model_class.human_attribute_name(:date) %></th>
      <th><%= model_class.human_attribute_name(:order_id) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= link_to line_item.id, line_item_path(line_item) %></td>
        <td><%= line_item.pallet.pallet_name %></td>
        <td><%= line_item.quantity %></td>
        <td align="right"><%= number_to_currency(line_item.line_item_total) %></td>
        <td><%= line_item.date %></td>
        <td><%= line_item.order_id %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      line_item_path(line_item), :class => 'btn btn-success btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_line_item_path(line_item), :class => 'btn btn-update btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      line_item_path(line_item),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_line_item_path,
            :class => 'btn btn-primary' %>
</div>

app/views/line_items/new.html.erb
<%- model_class = LineItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/line_items/show.html.erb
<%- model_class = LineItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
  <hr>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:pallet_id) %>:</strong></dt>
  <dd><%= @line_item.pallet.pallet_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:quantity) %>:</strong></dt>
  <dd><%= @line_item.quantity %></dd>
  <dt align="right"><strong><%= model_class.human_attribute_name(:line_item_total) %>:</strong></dt>
  <dd><%= number_to_currency(@line_item.line_item_total) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= @line_item.date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:order_id) %>:</strong></dt>
  <dd><%= @line_item.order_id %></dd>
</dl>
<br><br>

<%= link_to t('.back', :default => t("helpers.links.back")),
              line_items_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_line_item_path(@line_item), :class => 'btn btn-update' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              line_item_path(@line_item),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>